identifier_name:
    min_length: 1
    error: 4
    max_length: 40
    warning: 40
    error: 50
    excluded:
        - id
        - URL
        - GlobalAPIKey

disabled_rules:
- line_length
- trailing_whitespace
- todo
included:
excluded:
- Pods
- PhotoTag/App/AppDelegate.swift
- PhotoTag/App/SceneDelegate.swift
- PhotoTag/App
