# Uncomment the next line to define a global platform for your project
# platform :ios, '9.3'

target 'PhotoTag' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint'
  pod 'YPImagePicker'
  
  # Pods for PhotoTag

  target 'PhotoTagTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
